# Generated by Django 5.0.2 on 2024-03-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_students',
            field=models.PositiveIntegerField(verbose_name='макс. человек'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_students',
            field=models.PositiveIntegerField(verbose_name='мин. человек'),
        ),
    ]
